Pr batch example
pashagolub/pgxmock pull request #212
Opened 2024-07-19 14:38 UTC by giuliocn

2024-07-19 15:04 UTC, pashagolub commented
Why didn't you just reopen the previous pull request?

2024-07-19 15:08 UTC, pashagolub requested changes

2024-07-19 15:08 UTC, pashagolub commented on examples/batch/batch.go
> +	}
Why do you think we need to start a new transaction here? Batch is executed within a single transaction anyway. Do you plan to add other statements?

2024-07-19 15:08 UTC, pashagolub commented on examples/batch/batch_test.go
> +	mock.ExpectRollback()
What do you mean `TODO`? It's already there for several months, I believe

2024-07-19 19:17 UTC, giuliocn commented
> Why didn't you just reopen the previous pull request?

@pashagolub I have no right to re-open closed PR in this repository. I cannot see the button near "Comment".

2024-08-01 10:08 UTC, giuliocn commented
The example could be completed by serving all the results within an HTML page. What Do you think?

2024-08-19 11:04 UTC, pashagolub commented
Sorry for delay with answer.

I want examples to be as real as possible showing the real life use cases. That why I don't buy this one:
```go
	example.batch.Queue("SELECT * FROM ledger")
	example.batch.Queue("SELECT * FROM ledger WHERE amount = 1")
```

I will never in my life execute such a batch. Why? The first result set has it all.

2024-08-31 07:10 UTC, pashagolub commented
Tests failed and coverage is below threshold.

```sh

=== RUN   TestExpectBatch
--- PASS: TestExpectBatch (0.00s)
=== RUN   TestExpectBegin
    .\pgxmock\examples\batch\batch_test.go:50: there were unfulfilled expectations: there is a remaining expectation which was not matched: ExpectedBegin => expecting call to Begin() or to BeginTx()
--- FAIL: TestExpectBegin (0.00s)
FAIL
coverage: 6.7% of statements
FAIL	github.com/pashagolub/pgxmock/v4/examples/batch	0.029s
```

2024-08-31 07:36 UTC, pashagolub requested changes

2024-08-31 07:36 UTC, pashagolub commented on examples/batch/batch.go
> +	(` + strings.Join(fields[:4], ", ") + ");"
We don't do parameters concatenation, this is the possible place for SQL injection. We should use parameterized queries.

2024-08-31 07:36 UTC, pashagolub commented on examples/batch/batch.go
> +	example.insertRow(
Why we insert here and in `databaseSetup()`?

2024-08-31 07:36 UTC, pashagolub commented on examples/batch/batch.go
> +func (ex *ExampleBatch) requestBatch() (err error) {
I don't see any need in this function. Let's keep it simple

2024-08-31 07:36 UTC, pashagolub commented on examples/batch/batch.go
> +func (ex *ExampleBatch) insertRow(fields ...string) (err error) {
I don't see any value in `insertRow` function. And it's not covered by tests. It's better to remove it and keep things simple

2024-08-31 07:36 UTC, pashagolub commented on examples/batch/batch.go
> +	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
Nor `Begin` neither `Exec` used anywhere in code. Although this is not an error, we want to show our user that interfaces must be minimal

2024-09-05 17:23 UTC, giuliocn commented
@pashagolub Can you explain in what order a single row is retrieved with `BatchResults`? Can I consume a `Rows` object independently for each query? 

Thanks for your comments. 💡

2024-09-06 06:58 UTC, pashagolub commented
Yes, this is the idea behind the batch. You send all queries at once and then receive all results at once. And you are free to work with every result set as you wish.

If the example below the magic of sending and execution happened during `SendBatch()`. And then you just work with results you got back firing `results.Exec()`. **This is not you really execute** something, it's just to tell pgx you treat all statements as `Exec()`. But, of course, you can change it to `Query()` or even `QueryRow()`, see [here](https://github.com/jackc/pgx/blob/v5.6.0/batch.go#L80).

```go
func (pg *postgres) BulkInsertUsers(ctx context.Context, users []model.User) error {
  query := `INSERT INTO users (name, email) VALUES (@userName, @userEmail)`

  batch := &pgx.Batch{}
  for _, user := range users {
    args := pgx.NamedArgs{
      "userName": user.Name,
      "userEmail": user.Email,
    }
    batch.Queue(query, args)
  }
  
  results := pg.db.SendBatch(ctx, batch)
  defer results.Close()

  for _, user := range users {
    _, err := results.Exec()
    if err != nil {
      var pgErr *pgconn.PgError
      if errors.As(err, &pgErr) && pgErr.Code == pgerrcode.UniqueViolation {
          log.Printf("user %s already exists", user.Name)
          continue
      }

      return fmt.Errorf("unable to insert row: %w", err)
    }
  }

  return results.Close()
}
```

2024-09-19 12:42 UTC, pashagolub commented on examples/batch/batch.go
> +	})
I don't buy it. It should be one query
```sql
SELECT title, authors, subject, description FROM metadata
```

This is bad example.

2024-09-19 12:42 UTC, pashagolub commented on examples/batch/batch.go
> +}
Useless piece of code. No purpose. No meaning.

2024-09-19 12:42 UTC, pashagolub commented on examples/batch/batch.go
> +}
I don't understand the meaning of this.

2024-09-19 12:44 UTC, pashagolub commented
Unfortunately, I can't accept this work. This is not a proper example of using `pgx.Batch`. 
Thanks for your time.

2024-09-19 12:44 UTC, closed without merging